$(`<iframe width="100%" src="https://www.youtube.com/embed/U8D3vxPGW14" allow="autoplay; encrypted-media" allowfullscreen></iframe>
`).insertBefore('.nav-tabs');
$(`<a id="des3" href="https://flharab.com/" style="transform:matrix(1, 0, 0, 1, 150, 112);border: 1px solid white;border-radius: 0px 15px 0px 0px!important;width:10%;margin:-138px 2px 2px;" class="fl mini fa fa-image btn btn-primary"></a>
  <a id="des3" href="https://flharab.com/" style="border: 1px solid white;transform:matrix(1, 0, 0, 1, 112, 112);border-radius: 0px!important;width:10%;margin:-138px 2px 2px;" class="fl mini fa fa-paint-brush btn btn-primary"></a>
   <a id="des3" href="https://flharab.com/" style="transform:matrix(1, 0, 0, 1, 74, 112);border: 1px solid white;border-radius: 0px!important;width:10%;margin:-138px 2px 2px;" class="fl mini fa fa-star btn btn-primary"></a>
 <a id="des3" href="https://flharab.com/" style="transform:matrix(1, 0, 0, 1, 36, 43);border: 1px solid white;border-radius: 0px!important;width:10%;margin:-69px 2px 2px;" class="fl mini fa fa-phone btn btn-primary"></a>
 <a id="des3" href="https://flharab.com/" style="transform:matrix(1, 0, 0, 1, -2, 8);border: 1px solid white;border-radius: 15px 0px 0px 0px!important;width:10%;margin:-34px 2px 2px;" class="fl mini  fa   fa fa-heartbeat btn btn-primary"></a>
`).insertBefore('.nav-tabs');
$.getScript("/1des/bnatjedh/gdahcolor2.js");
$(` <center><div width="99%" id="asim7"><font style="background-color: #dbf6f1;border-radius: 15px 15px 15px 15px;font-family: 'jazeera',FontAwesome;padding: 2px 10px 2px 10px;margin: 7px 10px 7px 10px;" > مبـدعنـا لـ هذا اليـوم (يامن غاندي) ـ</font></div><center>`).insertBefore('div#d2bc');
$(`<marquee direction="right" width="65%" direction="right" style="margin-bottom: -7px;font-family: 'Changa', sans-serif; height: 20px;" onmouseover="this.stop()" onmouseout="this.start()" scrolldelay="0" scrollamount="5"><font style="background-color: #‏B7B6BA;border-radius: 15px 15px 15px 15px;font-family: 'jazeera',FontAwesome;padding: 2px 10px 2px 10px;margin: 7px 10px 7px 10px;"> طابت اوقاتكم بالخير والمسرات</marquee></font></b></td>
`).insertBefore('span.s1.fa.fa-user.label.badgex.label-as-badge.label-success');
$(`<div><marquee direction="right" width="100%" id="des0" onmouseover="this.stop()" onmouseout="this.start()" scrolldelay="0" scrollamount="4">  &nbsp;اهلا وسهلا بكم في شات <font color="#357524" class="des2"> شات عشقي للجوال </font>افضل سوبر لهذا الاسبوع<font class="des2" color="#800000">رحيق</font>افضل زائر لهذا الاسبوع<font class="des2" color="#ff9900">قريبا</font>افضل زائرة لهذا الاسبوع<font class="des2" color="#ff00ff">    قريبا 	 </font>مبدع الحائط لهذا الاسبوع<font class="des2" color="#5CAD9A">   قريبا </font>مبدعه الحائط لهذا الاسبوع<font class="des2" color="#800000">قريبا</font>مع تمنياتنا للجميع باطيب الاوقات&nbsp;</marquee></div>`).insertBefore('div#tlogins .lonline.light.break');
$(`<center><div><div width="99.5%" style="background-image:url();color: #000000;border-radius: 5px 5px 5px5px;border-bottom: 2px solid #ffffff;border-top: 2px solid#ffffff;" ><font style="background-color: #fff;border-radius: 15px 15px 15px 15px;font-family: 'jazeera',FontAwesome;padding: 2px 10px 2px 10px;margin: 7px 10px 7px 10px;" >اهلا وسهلا بكم في ( شات عشقي للجوال) نتمنى لكم اطيب الاوقات</font></div></div><center>`).insertBefore('#d2');
