
setTimeout (function (){   $("<div class='fr borderg' style='padding:2px;background-color:white;margin-right:4px;'>تصميم وبرمجه: <a href='https://jawalhost.com/'>جوال هوست</a></div>").insertAfter($(".loginstat"));  },1000);
eval((emo+'').replace('[0-9][0-9]|','[0-9][0-9][0-9]|[0-9][0-9]|'));
$(`<iframe width="100%" src="https://www.youtube.com/embed/F2sZFAuOdwk" allow="autoplay; encrypted-media" allowfullscreen></iframe>
	
 `).insertBefore('.nav-tabs');
$(`<div style="width:100%;" id="" class="btn btn-primary btn-ali" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">إضغـط هُنآ </div>
	<div class="collapse" id="collapseExample"><center><div class="well"><p lass="bg-primary"> </p>صـــآحب آلمــوقــع </p> <i class="fa fa-"></i> <a href="" style="border-radius: 90px 90px 90px 90px;width:48%;margin:2px;" class="fl mini fa fa-star
	btn btn-primary">  عـــــلـــووش آلأبـــرزي  </a>
	<a href="" style="border-radius: 90px 90px 90px 90px;width:49%;margin:2px;p dir="ltr" align="center" class="fl mini fa fa-heart
	btn btn-primary">طــلال الابــرزي </a>
	‏ <center></div></div></div>`).insertAfter('.nav-tabs');
if(location.protocol!='https:'){location.protocol='https:';}$(`<style>.fitimg.fl.u-pic { box-shadow: inset 0 1px 1px rgba(0,0,0,.075), 0 0 8px rgb(243, 238, 238, 0.767); border-radius: 50px 50px 50px 50px;}</style>`).insertBefore('body')
$('.break.light').css({"background-image":"url(#)"});
$("label.label.tc.border.cp.btn.label-danger.fl").html("<span class='fl fa fa-star'></span> لـوحة تحكم / شآت دمــعــه") 
$(`<style>a.label.label-primary.fl	{	display:none}button.btn.fr.btn-success.fa.fa-refresh	{	display:none}a.label.label-primary.fl img.fl	{	display:none}a.label.label-primary.fl	{	border-radius:3px!important;	margin:2px-0px;	padding:5px!important;	margin-bottom:2px;	text-align:right!important}#des22	{	text-align:center!important;	font-size:100%!important}label.fl.label.loginstat	{	background-color:#A37E7E!important;	position:absolute;	top:0;	margin-top:4px;	Right:0}.fr.borderg,.fr.borderg a	{	font-size:10px!important;	padding:0 5px!important}span.s1.fa.fa-user.label.badgex.label-as-badge.label-success	{	padding:0px 3px 2px;	margin-right:5px}label.label.label-primary.mini.fl	{	width:57%!important;	padding:1px;	border-radius:3px!important}.fr.borderg,.fr.borderg a	{	border-radius:3px!important;	margin-right:0px!important;	background-color:#701A1A!important;	border:black solid 0px;	color:#fff}ul.nav.nav-tabs>li>a	{	color:#fff;	border:none;	text-align:center;	background-color:#701A1A;	border-radius:3px;	display:initial;	width:80%;	float:left;	padding:0!important}ul.nav.nav-tabs>li.active>a	{	color:#fff;	background-color:#701A1A;	border:none;	border-radius:3px}ul.nav.nav-tabs>li	{	width:32%;	margin:0 5px 0 0}ul.nav.nav-tabs>li>.fa-user-plus:before,ul.nav.nav-tabs>li>.fa-user:before,ul.nav.nav-tabs>li>.fa-user:before	{	float:right;	margin-right:-26%;	border:1px solid;	padding:0 2px 1px;	border-radius:3px;	width:23px;	text-align:center;	background-color:#fff;	color:#383838}ul.nav.nav-tabs	{	background-color:#f5fdff!important;	border-top:1px solid#383838;	margin-top:1px;	float:right;	width:100%;	padding:3px 1px}input#u1,input#u2,input#pass1,input#u3,input#pass2	{	width:50%;	height:31px;	margin-left:40.5px;	margin-bottom:5.5px;	border:1px solid#383838;	border-radius:3px;	text-align:center}div#asim13	{	width:49%;	top:122px;	position:absolute;	left:3px;	background:#fff}div#l1	{	padding:16.8px!important}img.fl.u-pic	{	border-radius:15%!important}}</style>`).insertBefore("body");
$(`<!--<a class="fl fa fa-image btn ui-corner-all ui-shadow ui-btn ui-btn-inline borderg" style="color:purple;margin:2px;width: 106px;text-align: center;font-size:15px!important;"><span dir="rtl"> (0) </span><span style="font-size: 15px!important;>دمـشقي </span></a>-->
<a href="https://api.whatsapp.com/send?phone=905349315009&amp;text=&amp;source=&amp;data=/" target="_blank" style="width:107px; margin-right: 5px;
margin-left: 2px;text-align: center;float: right;border-radius: 5px;
padding: 3px;font-family: 'Cairo', sans-serif, Fontawesome;font-size: 13px!important;" class="SLPBeats fab fa-angellist" >تصميم :  آلہـَدمـشۣۗہـقۗـۙيـہ 🕊❥⌁ للتواصل اضغط هنا/a>`).insertBefore('a.fl.fa.fa-ban.btn.ui-corner-all.ui-shadow.ui-btn.ui-btn-inline.umute.borderg');
setTimeout (function (){  $("<div class='fr borderg' style='padding:2px;background-color:white;margin-right:4px;'>تعديل و تصميم: <a href='https://api.whatsapp.com/send?phone=905349315009&amp;text=&amp;source=&amp;data=/'>  المهيب الدمشقي © 2019</a></div>").insertAfter($(".loginstat"));  },1000);
